<?php 
include ('header.php'); ?>
<!DOCTYPE html>
<html>
<head>
	<title></title>
</head>
<body>
	<?php include ('nav.php'); ?>
  <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit"><font color="white" ="">Search</button>
    </form>

    <div class="inner-content">
    
      <p><span style="font-size: 12px;">Selamat datang di website www.Dinus Shop.co.id dan / atau aplikasi mobile Dinus Shop. Silahkan membaca Syarat Penggunaan ini dengan seksama. Syarat Penggunaan ini mengatur penggunaan dan akses Platform (didefinisikan di bawah) dan penggunaan layanan (didefinisikan di bawah). Dengan mengakses Platform dan / atau menggunakan Layanan, Anda setuju untuk terikat dengan Syarat Penggunaan ini. Jika Anda tidak menyetujui Syarat Penggunaan ini, maka Anda jangan/berhenti mengakses dan/atau menggunakan Platform atau Layanan ini.</span></p>
<p><span style="font-size: 12px;">Akses atas password dan penggunaan password dilindungi dan/atau area tertentu yang diterlindungi pada Platform dan/atau penggunaan Layanan dibatasi hanya untuk Pelanggan yang memiliki akun saja. Anda tidak diperbolehkan memperoleh atau berusaha memperoleh akses tidak sah ke area Platform dan / atau Layanan ini, atau ke area informasi lain yang dilindungi, dengan cara apapun yang tanpa ijin penggunaan khusus oleh kami. Pelanggaran terhadap ketentuan ini merupakan pelanggaran yang didasarkan pada hukum Indonesia dan / atau undang-undang dan peraturan yang berlaku.</span></p>
<p><span style="font-size: 12px;">Jika Anda berusia di bawah 18 tahun: Anda harus memperoleh persetujuan dari orang tua atau wali Anda, penerimaan ataupersetujuan orang tua/wali terhadap Persyaratan Penggunaan ini beserta persetujuan mereka untuk mengambil tanggung jawab untuk: </span></p>
<p><span style="font-size: 12px;">	(i) tindakan Anda; </span></p>
<p><span style="font-size: 12px;">	(ii) biaya yang terkait dengan penggunaan setiap Layanan atau pembelian Produk; dan </span></p>
<p><span style="font-size: 12px;">	(iii) penerimaan dan kepatuhan Anda sesuai dengan Syarat &amp; Ketentuan Penggunaan ini. Jika Anda tidak memiliki izin dari orang tua atau wali, Anda harus berhenti menggunakan / mengakses platform dan berhenti menggunakan Layanan ini.</span></p>
<p><span style="font-size: 12px;">	1.	Definisi &amp; Interpretasi Kecuali jika didefinisikan lain, definisi dan ketentuan pada Lampiran 1 akan berlaku untuk Syarat Penggunaan ini.</span></p>
<p><span style="font-size: 12px;">	2.	Penggunaan umum Layanan dan/atau akses atas Platform</span></p>
<p><span style="font-size: 12px;">		1.	Pedoman penggunaan Platform dan/atau Layanan: Anda setuju untuk mematuhi setiap dan semua pedoman, pemberitahuan, aturan operasi dan kebijakan dan instruksi yang berkaitan dengan penggunaan Layanan dan/atau akses ke Platform, serta setiap perubahan-nya, yang dikeluarkan oleh kami, dari waktu ke waktu. Kami berhak untuk merevisi pedoman, pemberitahuan, aturan operasi, kebijakan dan instruksi sewaktu-waktu dan Anda dianggap mengetahui dan tunduk oleh setiap perubahan tersebut di atas setelah ada-nya pemberitahuan atau publikasi atas perubahan tersebut di Platform atau pemberitahuan melalui media lain.</span></p>
<p><span style="font-size: 12px;">		2.	Kegiatan terlarang: Anda setuju dan TIDAK akan melakukan :</span></p>
<p><span style="font-size: 12px;">			1.	Berpura-pura sebagai orang lain/entitas, atau memberikan keterangan yang salah, atau mengaku sebagai orang lain atau kelompok tertentu;</span></p>
<p><span style="font-size: 12px;">			2.	Menggunakan Platform atau Layanan untuk tujuan yang melanggar hukum (illegal);</span></p>
<p><span style="font-size: 12px;">			3.	Berusaha untuk mendapatkan akses tidak sah atau mengganggu atau mengacaukan sistem komputer atau jaringan yang terhubung dengan Platform atau Layanan;</span></p>
<p><span style="font-size: 12px;">			4.	Mengumumkan (posting), mempromosikan atau mengirimkan Materi Terlarang apapun melalui Platform atau Layanan;</span></p>
<p><span style="font-size: 12px;">			5.	Mengganggu pemanfaatan dan pemakaian dari Platform atau Layanan;</span></p>
<p><span style="font-size: 12px;">			6.	Menggunakan atau unggah atau meng-upload perangkat lunak atau material yang mengandung / dicurigai mengandung virus, komponen merusak, kode berbahaya atau komponen berbahaya dengan cara apapun yang dapat merusak data atau mengakibatkan kerusakan Platform atau mengganggu pengoperasian komputer Pelanggan lain atau perangkat mobile atau Platform atau Layanan; dan</span></p>
<p><span style="font-size: 12px;">			7.	Menggunakan Platform atau Layanan diluar dari aturan / kebijakan penggunaan setiap jaringan komputer yang terhubung, setiap standar Internet yang berlaku dan hukum yang berlaku lainnya.</span></p>
<p><span style="font-size: 12px;">		3.	Ketersediaan Platform dan Layanan: Kami dapat meningkatkan, memodifikasi, menghentikan sementara, menghentikan penyediaan, menghapus, baik secara keseluruhan atau sebagian dari Platform atau Layanan, tanpa memberikan alasan &amp; pemberitahuan sebelumnya, dan tidak bertanggung jawab jika peningkatan, modifikasi, suspensi atau penghapusan tersebut mencegah Anda mengakses Platform atau bagian dari Layanan.</span></p>
<p><span style="font-size: 12px;">		4.	Berhak, namun tidak berkewajiban, untuk memantau konten: Kami berhak, tetapi tidak wajib untuk:</span></p>
<p><span style="font-size: 12px;">			1.	Memantau, menyaring atau mengontrol setiap kegiatan, isi atau materi pada Platform dan / atau melalui Layanan. Atas kebijakan kami sendiri, kami dapat menyelidiki setiap pelanggaran terhadap syarat dan ketentuan yang tercantum di sini dan dapat mengambil tindakan apapun yang dianggap sesuai atau tepat;</span></p>
<p><span style="font-size: 12px;">			2.	Mencegah atau membatasi akses Pelanggan untuk Platform dan/atau Jasa;</span></p>
<p><span style="font-size: 12px;">			3.	Melaporkan kegiatan yang dicuragai sebagai pelanggaran terhadap hukum yang berlaku, undang-undang atau peraturan kepada pihak yang berwenang serta bekerja sama dengan pihak berwenang tersebut; dan/atau</span></p>
<p><span style="font-size: 12px;">			4.	Meminta informasi dan data dari Anda sehubungan dengan penggunaan Layanan dan/atau akses Platform setiap saat, dan sebagai pelaksanaan hak kami jika Anda menolak untuk memberikan/mengungkapkan informasi/data tersebut, atau jika Anda memberikan informasi tidak akurat, menyesatkan, penipuan data dan/atau informasi atau jika kami memiliki alasan yang cukup mencurigai Anda telah menyediakan informasi tidak akurat, menyesatkan atau penipuan data dan/atau informasi.</span></p>
<p><span style="font-size: 12px;">			5.	Kebijakan Privasi: Penggunaan Anda atas Layanan dan/atau akses Anda ke Platform juga tunduk pada Kebijakan Privasi sebagaimana tercantum di https://www.Dinus Shop.co.id/privacy-policy/</span></p>
<p><span style="font-size: 12px;">			6.	Syarat &amp; Ketentuan Penjualan: Pembelian Produk apapun akan tunduk pada Syarat &amp; Ketentuan Penjualan sebagaimana tercantum di https://www.Dinus Shop.co.id/terms-of-use/#tos Jika Anda menggunakan Voucher, maka Syarat &amp; Ketentuan Voucher sebagaimana dimaksud pada https://www.Dinus Shop.co.id/terms-of-use/#tov</span></p>
<p><span style="font-size: 12px;">			7.	Ketentuan lain: selain Syarat Penggunaan ini, penggunaan aspek-aspek tertentu dari Materi dan Layanan, lebih komprehensif atau versi terbaru dari Materi yang ditawarkan oleh kami atau sub-kontraktor yang ditunjuk, dapat dikenakan syarat dan ketentuan tambahan, yang akan berlaku sepenuhnya.</span></p>
<p></p>
<p><span style="font-size: 12px;">	3.	Penggunaan Layanan</span></p>
<p><span style="font-size: 12px;">		1.	Penerapan Klausul ini: Selain dari semua syarat dan ketentuan di Syarat Penggunaan ini, ketentuan dalam Pasal ini 3 merupakan ketentuan – ketentuan tambahan yang spesifik berlaku atas penggunaan Anda atas Layanan.</span></p>
<p><span style="font-size: 12px;">		2.	Pembatasan: Penggunaan Layanan terbatas pada Pelanggan yang sah yang berada pada usia dewasa secara hukum dan yang memiliki kapasitas hukum untuk masuk/membuat kesepakatan/perjanjian dan mengikatkan diri berdasarkan hukum yang berlaku. Pelanggan yang melanggar syarat dan ketentuan yang tercantum di sini serta Pelanggan yang ditangguhkan secara permanen atau sementara dari penggunaan setiap Layanan tidak diperbolehkan menggunakan Layanan meskipun mereka memenuhi persyaratan Klausul 3.2 ini.</span></p>
<p><span style="font-size: 12px;">		3.	Persyaratan penggunaan umum: Dengan ini Anda setuju:</span></p>
<p><span style="font-size: 12px;">			1.	Untuk selalu mengakses dan/atau menggunakan Layanan hanya untuk tujuan yang tidak melanggar hukum, dan dengan cara yang sah dan selanjutnya setuju untuk melakukan kegiatan yang berkaitan dengan Layanan dengan itikad baik; dan</span></p>
<p><span style="font-size: 12px;">			2.	Memastikan bahwa setiap informasi atau data yang Anda berikan/umumkan/posting atau yang dimunculkan di Platform sehubungan dengan Layanan adalah akurat dan setuju untuk bertanggung jawab atas informasi dan data tersebut.</span></p>
<p><span style="font-size: 12px;">			3.	Deskripsi Produk: Kami selalu berusaha untuk memberikan deskripsi yang akurat tentang Produk, namun tidak bertanggungjawab atas jaminan bahwa deskripsi tersebut akurat, terkini atau bebas dari kesalahan.</span></p>
<p><span style="font-size: 12px;">			4.	Harga Produk: Semua Harga terdaftar termasuk PPN, kecuali penjual bukan PKP. Kami berhak untuk mengubah Daftar Harga setiap saat tanpa memberikan alasan apapun atau pemberitahuan sebelumnya.</span></p>
<p><span style="font-size: 12px;">			5.	Vendor Pihak Ketiga: Dengan ini Anda mengetahui bahwa atas keberadaan pihak – pihak lain selain Dinus Shop (Vendor Pihak Ketiga) yang mendaftar dan menjual produk di Platform. Produk yang dijual di Platform oleh Dinus Shop atau Vendor Pihak Ketiga dapat dicantumkan pada daftar Produk pada laman web. Untuk menghindari keraguan, setiap transaksi / kesepakatan atas penjualan produk Vendor Pihak Ketiga kepada Pelanggan, adalah kesepakatan atau perjanjian yang dibuat langsung oleh Pelanggan dan Vendor Pihak Ketiga, yang mengikat hanya antara Pelanggan dan Vendor Pihak Ketiga. </span></p>
<p><span style="font-size: 12px;">	4.	Pelanggan dengan akun Dinus Shop</span></p>
<p><span style="font-size: 12px;">		1.	Username/Password: Layanan – layanan tertentu yang tersedia di Platform memerlukan pembuatan akun atau memerlukan Anda untuk memberikan Data Pribadi Anda. Jika Anda ingin membuat akun Dinus Shop, Username dan Password dapat berupa: (i) ditentukan dan diberikan oleh kami kepada Anda; atau (ii) Anda tentukan/berikan dan diterima oleh kami berdasarkan kebijakan mutlak kami sehubungan dengan penggunaan Layanan dan/atau akses ke Platform yang relevan. Kami sewaktu waktu dengan kebijakan kami, meminta Anda memperbaharui Data Pribadi Anda atau dapat membatalkan Username dan/atau Password tanpa pemberitahuan terlebih dahulu dan tidak bertanggung jawab atas Kerugian (apabila ada) yang diderita oleh Anda, atau disebabkan oleh Anda, atau yang timbul dari pembatalan, atau sehubungan dengan pembatalan, atau dari dasar/alasan permintaan pembatalan atau pembatalan tersebut. Anda dengan ini setuju untuk merubah/memperbaharui Password Anda secara berkala dan untuk menjaga Username dan Password secara rahasia dan bertanggung jawab atas keamanan akun Anda dan bertanggung jawab atas pengungkapan atau penggunaan (apakah penggunaan tersebut diijinkan atau tidak) dari Username dan/atau password Anda. Anda harus segera hubungi kami jika Anda mengetahui atau memiliki alasan untuk mencurigai bahwa kerahasiaan Username dan/atau Password Anda terganggu atau jika terjadi penggunaan yang tidak sah dari Usernamedan/atau Password atau jika Data Pribadi Anda butuh diperbaharui.</span></p>
<p><span style="font-size: 12px;">		2.	Pengakuan penggunaan/akses: Anda setuju dan mengetahui bahwa setiap penggunaan Layanan dan/atau akses ke Platform dan informasi, data atau komunikasi merujuk Username dan Password anda akan dianggap, sebagai:</span></p>
<p><span style="font-size: 12px;">			1.	Akses terhadap Platform dan/atau penggunaan Layanan oleh Anda; atau</span></p>
<p><span style="font-size: 12px;">			2.	Posting, pengumuman/pengungkapan, pemberian: informasi, data atau komunikasi, yang sah dikeluarkan oleh Anda.</span></p>
<p><span style="font-size: 12px;">			3.	Dengan ini Anda setuju untuk tunduk atas akses Platform dan/atau penggunaan Layanan (apakah akses atau penggunaan tersebut dengan ijin Anda atau tidak) dan Anda setuju bahwa kami berhak (tetapi tidak berkewajiban) untuk berpegangan dan menganggap bahwa penggunaan atas nama Username dan/atau Password Anda adalah dilakukan oleh Anda sendiri (sepanjang tidak ada laporan pemakaian tidak sah sebelumnya atas akun Anda yang telah terbukti) dan berhak menyimpulkan bahwa pengunaan/kegiatan tersebut dilakukan atau dikirimkan oleh Anda dan meminta pertanggungjawaban Anda. Anda selanjutnya setuju dan mengakui bahwa Anda terikat dan bertanggungjawa sepenuhnya mengganti atau atas kerugian yang timbul disebabkan setiap penggunaan setiap Layanan dan/atau akses ke Platform atas nama Username dan Password Anda.</span></p>
  
  </div>
</nav>
</body>
</html>
<?php 
include('footer.php'); ?>
